// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251005234403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GraphQLDemo.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 2,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            Id = 4,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jane Austen"
                        });
                });

            modelBuilder.Entity("GraphQLDemo.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Title = "Pride and Prejudice"
                        });
                });

            modelBuilder.Entity("GraphQLDemo.Book", b =>
                {
                    b.HasOne("GraphQLDemo.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GraphQLDemo.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
